### ISSUE TITLE
Problem with numbers

### ISSUE THREAD

**Issue by ManuelLeitner** [rstropek-teaching/product-catalog-quiz-5ahif-ManuelLeitner#1]
I can't input the "unitPrice" with the German decimal format as the validation fails. So I have to use the English format, which will later be parsed in a wrong way. What could I do in order to solve that?

**Comment by rstropek** [comment]
@ManuelLeitner ASP.NET Core allows to set the culture in the startup code. Add e.g. the following code to your `Configure` method in the *Startup.cs* file **before** `UseMvc`:

```
var supportedCultures = new List<CultureInfo> { new CultureInfo("en") };
app.UseRequestLocalization(new RequestLocalizationOptions
{
    SupportedCultures = supportedCultures,
    SupportedUICultures = supportedCultures,
    DefaultRequestCulture = new RequestCulture("en")
});
```

Note that this sets the culture to English. Using a German culture even for client-side validations is quite tricky. I would not recommend doing this in this exercise. I would have to spend some time Google'ing the challenge myself. We typically do not use ASP.NET Core's built-in client-side validations but rely on custom-built validations instead.

Does that help?

Regards,
Rainer Stropek.

**Comment by ManuelLeitner** [comment]
thank you
